### PR TITLE
Implementation of statistics cliente module.

### PR DESCRIPTION
**Pull request by rlimonta**

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @rlimonta 

Can you add the license header from https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8 to each Java file ?

**Comment by deruelle** [comment]
We should also allow the path at https://github.com/RestComm/commons/pull/1/commits/e7484b5112ed6bdd78a6c041c9e382951f7bb422#diff-4dc3fe7c3d3bcf99ba22cd5396f199a4R29 to be configured programmatically.

**Comment by deruelle** [comment]
@rlimonta let me know when you have been able to fix the above.

**Comment by rlimonta** [comment]
Done.

2016-07-12 4:56 GMT-03:00 Jean Deruelle notifications@github.com:

> Thanks @rlimonta https://github.com/rlimonta
> 
> Can you add the license header from
> https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8
> to each Java file ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/RestComm/commons/pull/1#issuecomment-231965736, or mute
> the thread
> https://github.com/notifications/unsubscribe/ASRSjXvYkkgaYYZWI4eHZiE4lIVcaC9Sks5qU0iZgaJpZM4JJ0XJ
> .

## 

Ricardo Limonta

**Comment by rlimonta** [comment]
Jean, it´s done.

Regards.

Ricardo Limonta

2016-07-12 5:01 GMT-03:00 Jean Deruelle notifications@github.com:

> @rlimonta https://github.com/rlimonta let me know when you have been
> able to fix the above.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/RestComm/commons/pull/1#issuecomment-231966814, or mute
> the thread
> https://github.com/notifications/unsubscribe/ASRSjSRf54_Qugv7rX1nXZX4TnvIq9lOks5qU0nMgaJpZM4JJ0XJ
> .

## 

Ricardo Limonta

**Comment by deruelle** [comment]
@rlimonta Can you sign the contributor license agreement at http://www.telestax.com/open-source/#Contribute so we can acknowledge your work at https://telestax.com/acknowledgements/ ?

**Comment by rlimonta** [comment]
Yes!

I would like to thank you for this opportunity.

I intend to contribute a lot to the project. We are building a new office
in Brazil, and will soon have a development team.

I believe we can contribute more in the near future.

Best regards.

Ricardo Limonta

2016-07-12 13:16 GMT-03:00 Jean Deruelle notifications@github.com:

> Can you sign the contributor license agreement at
> http://www.telestax.com/open-source/#Contribute so we can acknowledge
> your work at https://telestax.com/acknowledgements/ ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/RestComm/commons/pull/1#issuecomment-232098264, or mute
> the thread
> https://github.com/notifications/unsubscribe/ASRSjUKEELJandKmlULOKxudxNY7dZCoks5qU73YgaJpZM4JJ0XJ
> .

## 

Ricardo Limonta

**Comment by deruelle** [comment]
Thanks @rlimonta ! Looking forward to more contributions. 

you have been acknowledged at https://telestax.com/acknowledgements/

**Pull request merged**
